version: "3"
services:
    server:
        image: php:7.2-apache
        restart: always
        container_name: apache_server
        ports:
            - "8000:80"
        volumes:
            - ./apache/site/:/var/www